### PR TITLE
Some non-breaking changes

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- Remove `Update-EnvironmentVariables` function from Bootstrap.ps1
- Remove `Set-Service edgeupdate -Status stopped -StartupType disabled ; Set-Service edgeupdatem -Status stopped -StartupType disabled` since it has already been run while building the docker image

### CODE REVIEW

**Comment by vedantmgoyal9** [comment]
- Use PowerShell to block edge updates
- Remove EdgeBlocker.cmd
- Re-order statements in Dockerfile

**Comment by vedantmgoyal9** [comment]
I highly recommend testing the changes from this PR.

If @jedieaston doesn't have time, maybe @russellbanks can help? (I don't have docker installed on my windows pc)

**Comment by russellbanks** [comment]
```
Sending build context to Docker daemon  351.7kB
Step 1/17 : FROM mcr.microsoft.com/windows/server:ltsc2022 as wingettest
 ---> 947a3d88db90
Step 2/17 : USER ContainerAdministrator
 ---> Using cache
 ---> 52a8a2b512e0
Step 3/17 : WORKDIR C:\\wingetdev
 ---> Using cache
 ---> 2c4d76779b64
Step 4/17 : ADD "https://aka.ms/vs/16/release/vc_redist.x64.exe" "C:\\"
Downloading [==================================================>]  25.23MB/25.23MB

 ---> 697d97ec2065
Step 5/17 : ADD "https://github.com/jedieaston/winget-build/releases/latest/download/wingetdev.zip" "C:\\"
Downloading [==================================================>]  1.737MB/1.737MB

 ---> f2db9e5d3a18
Step 6/17 : ADD "Bootstrap.ps1", "Bootstrap.ps1"
ADD failed: file not found in build context or excluded by .dockerignore: stat Bootstrap.ps1,: file does not exist
```

**Comment by vedantmgoyal9** [comment]
@russellbanks now?

**Comment by russellbanks** [comment]
```
Step 11/17 : RUN wingetdev.exe install -s winget Microsoft.Edge
 ---> Running in bd315339f0eb
wingetdev.exe : The term 'wingetdev.exe' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ wingetdev.exe install -s winget Microsoft.Edge
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (wingetdev.exe:String) [], Comma
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

The command 'powershell -Command wingetdev.exe install -s winget Microsoft.Edge' returned a non-zero code: 1
```

I get this but I'm pretty sure I got this before so I would just comment out the line. Running without it gets this:

```
Step 13/16 : RUN Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\'
 ---> Running in b6d4a67255ec
Remove-Item : Cannot remove item C:\Program Files
(x86)\Microsoft\EdgeUpdate\1.3.135.41\msedgeupdateres_en.dll: Access to the
path 'msedgeupdateres_en.dll' is denied.
At line:1 char:1
+ Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\Edge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (msedgeupdateres_en.dll:FileIn
   fo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft
   .PowerShell.Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files
(x86)\Microsoft\EdgeUpdate\1.3.135.41: The process cannot access the file
'C:\Program Files (x86)\Microsoft\EdgeUpdate\1.3.135.41' because it is being
used by another process.
At line:1 char:1
+ Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\Edge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (1.3.135.41:DirectoryInfo) [Remove-I
   tem], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell
   .Commands.RemoveItemCommand
Remove-Item : Cannot remove item C:\Program Files (x86)\Microsoft\EdgeUpdate\:
The directory is not empty.
At line:1 char:1
+ Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\Edge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Program File...oft\EdgeUpdate\:D
   irectoryInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell
   .Commands.RemoveItemCommand
The command 'powershell -Command Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\'' returned a non-zero code: 1
```

**Review by jedieaston — CHANGES_REQUESTED** [review]
What @russellbanks brought up, and also, please put back the EdgeUpdate thing. Sometimes it doesn't work unless you do it at runtime (no, I don't know why. Guessing there's some other service that turns it back on.)

**Comment by vedantmgoyal9** [comment]
* Re-added `Set-Service edgeupdate -Status stopped -StartupType disabled ; Set-Service edgeupdatem -Status stopped -StartupType disabled` in Bootstrap.ps1
* Updated Dockerfile - Commented `wingetdev.exe install -s winget Microsoft.Edge` - the build fails with the following error.
```
PS C:\Users\vedan\Downloads> .\docker.exe build . -f .\OfficialDockerfile
Sending build context to Docker daemon  30.42MB
Step 1/17 : FROM mcr.microsoft.com/windows/server:ltsc2022 as wingettest
 ---> 5c74aa8a33c6
Step 2/17 : USER ContainerAdministrator
 ---> Using cache
 ---> 849e080b924e
Step 3/17 : WORKDIR C:\\wingetdev
 ---> Using cache
 ---> 16ae47804feb
Step 4/17 : ADD Bootstrap.ps1 .
 ---> Using cache
 ---> 6308b28a9adb
Step 5/17 : ADD https://aka.ms/vs/16/release/vc_redist.x64.exe .
Downloading [==================================================>]  25.23MB/25.23MB

 ---> Using cache
 ---> 05481ee58d35
Step 6/17 : ADD https://github.com/jedieaston/winget-build/releases/latest/download/wingetdev.zip .
Downloading [==================================================>]   1.74MB/1.74MB

 ---> Using cache
 ---> 5bbd5d732faf
Step 7/17 : SHELL [ "powershell", "-Command" ]
 ---> Using cache
 ---> 322eda41093c
Step 8/17 : RUN Expand-Archive -LiteralPath .\wingetdev.zip -DestinationPath . -Force ; Move-Item .\AppInstallerCLI\* .
 ---> Running in a6bac2e5c88c
Removing intermediate container a6bac2e5c88c
 ---> 589eca2bb146
Step 9/17 : RUN .\vc_redist.x64.exe /install /passive /norestart /log .\vc_redist.log
 ---> Running in 34be3f63337a
Removing intermediate container 34be3f63337a
 ---> 9c9bf291d93e
Step 10/17 : RUN .\wingetdev.exe settings --enable LocalManifestFiles
 ---> Running in 8b6e25abb938
Admin setting enabled.Removing intermediate container 8b6e25abb938
 ---> 2f79d891cb74
Step 11/17 : RUN .\wingetdev.exe install -s winget Microsoft.Edge
 ---> Running in 7adf74d2b5c8
Found an existing package already installed. Trying to upgrade the installed package...
A newer version was found, but the install technology is different from the current version installed. Please uninstall the package and install the newer version.
The command 'powershell -Command .\wingetdev.exe install -s winget Microsoft.Edge' returned a non-zero code: 1
```

**Comment by vedantmgoyal9** [comment]
The build succeeds now, a second review from @russellbanks would ensure no bugs 🐛 
```
PS C:\Users\vedan\Downloads> .\docker.exe build . -f .\OfficialDockerfile
Sending build context to Docker daemon  30.42MB
Step 1/16 : FROM mcr.microsoft.com/windows/server:ltsc2022 as wingettest
 ---> 5c74aa8a33c6
Step 2/16 : USER ContainerAdministrator
 ---> Using cache
 ---> 849e080b924e
Step 3/16 : WORKDIR C:\\wingetdev
 ---> Using cache
 ---> 16ae47804feb
Step 4/16 : ADD Bootstrap.ps1 .
 ---> Using cache
 ---> 6308b28a9adb
Step 5/16 : ADD https://aka.ms/vs/16/release/vc_redist.x64.exe .
Downloading [==================================================>]  25.23MB/25.23MB

 ---> Using cache
 ---> 05481ee58d35
Step 6/16 : ADD https://github.com/jedieaston/winget-build/releases/latest/download/wingetdev.zip .
Downloading [==================================================>]   1.74MB/1.74MB

 ---> Using cache
 ---> 5bbd5d732faf
Step 7/16 : SHELL [ "powershell", "-Command" ]
 ---> Using cache
 ---> 322eda41093c
Step 8/16 : RUN Expand-Archive -LiteralPath .\wingetdev.zip -DestinationPath . -Force ; Move-Item .\AppInstallerCLI\* .
 ---> Using cache
 ---> 589eca2bb146
Step 9/16 : RUN .\vc_redist.x64.exe /install /passive /norestart /log .\vc_redist.log
 ---> Using cache
 ---> 9c9bf291d93e
Step 10/16 : RUN .\wingetdev.exe settings --enable LocalManifestFiles
 ---> Using cache
 ---> 2f79d891cb74
Step 11/16 : RUN New-Item -Path HKLM:\\SOFTWARE\\Microsoft\\EdgeUpdate -Force
 ---> Running in 17b69bfc9472


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft


Name                           Property
----                           --------
EdgeUpdate


Removing intermediate container 17b69bfc9472
 ---> 537a0659cbed
Step 12/16 : RUN New-ItemProperty -Path HKLM:\\SOFTWARE\\Microsoft\\EdgeUpdate -Name DoNotUpdateToEdgeWithChromium -Value 1 -PropertyType DWord -Force
 ---> Running in 905611d4e129


DoNotUpdateToEdgeWithChromium : 1
PSPath                        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_
                                MACHINE\SOFTWARE\Microsoft\EdgeUpdate
PSParentPath                  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_
                                MACHINE\SOFTWARE\Microsoft
PSChildName                   : EdgeUpdate
PSDrive                       : HKLM
PSProvider                    : Microsoft.PowerShell.Core\Registry



Removing intermediate container 905611d4e129
 ---> f02975e46c17
Step 13/16 : RUN Set-Service -Name edgeupdate -Status Stopped -StartupType Disabled # stop edgeupdate service
 ---> Running in ae75cee06cb6
Removing intermediate container ae75cee06cb6
 ---> d6f63259d452
Step 14/16 : RUN Set-Service -Name edgeupdatem -Status Stopped -StartupType Disabled # stop edgeupdatem service
 ---> Running in 165c360786f4
Removing intermediate container 165c360786f4
 ---> c7df25a53be5
Step 15/16 : RUN Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\'
 ---> Running in 884edcc8a349
Removing intermediate container 884edcc8a349
 ---> 3033b1dab9e9
Step 16/16 : ENTRYPOINT ["powershell", "-File", "Bootstrap.ps1"]
 ---> Running in 2b4b0d039f3e
Removing intermediate container 2b4b0d039f3e
 ---> 138933c92150
Successfully built 138933c92150
PS C:\Users\vedan\Downloads>
```

**Comment by russellbanks** [comment]
```
Step 1/16 : FROM mcr.microsoft.com/windows/server:ltsc2022 as wingettest
 ---> 947a3d88db90
Step 2/16 : USER ContainerAdministrator
 ---> Using cache
 ---> 52a8a2b512e0
Step 3/16 : WORKDIR C:\\wingetdev
 ---> Using cache
 ---> 2c4d76779b64
Step 4/16 : ADD Bootstrap.ps1 .
 ---> 8dd97ac1acfb
Step 5/16 : ADD https://aka.ms/vs/16/release/vc_redist.x64.exe .
Downloading [==================================================>]  25.23MB/25.23MB

 ---> cd56f269b99a
Step 6/16 : ADD https://github.com/jedieaston/winget-build/releases/latest/download/wingetdev.zip .
Downloading [==================================================>]  1.741MB/1.741MB

 ---> 64cc8abebb67
Step 7/16 : SHELL [ "powershell", "-Command" ]
 ---> Running in 7605b0027eaf
Removing intermediate container 7605b0027eaf
 ---> 75612836da1b
Step 8/16 : RUN Expand-Archive -LiteralPath .\wingetdev.zip -DestinationPath . -Force ; Move-Item .\AppInstallerCLI\* .
 ---> Running in 7859c6c87d68
Removing intermediate container 7859c6c87d68
 ---> 897068693538
Step 9/16 : RUN .\vc_redist.x64.exe /install /passive /norestart /log .\vc_redist.log
 ---> Running in 83cd0d1d353c
Removing intermediate container 83cd0d1d353c
 ---> bedb4e888490
Step 10/16 : RUN .\wingetdev.exe settings --enable LocalManifestFiles
 ---> Running in b18bd7131293
Admin setting enabled.Removing intermediate container b18bd7131293
 ---> 12c7e4cafe44
Step 11/16 : RUN New-Item -Path HKLM:\\SOFTWARE\\Microsoft\\EdgeUpdate -Force
 ---> Running in 8863e245123b


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft


Name                           Property
----                           --------
EdgeUpdate


Removing intermediate container 8863e245123b
 ---> 6585031ae74c
Step 12/16 : RUN New-ItemProperty -Path HKLM:\\SOFTWARE\\Microsoft\\EdgeUpdate -Name DoNotUpdateToEdgeWithChromium -Value 1 -PropertyType DWord -Force
 ---> Running in 6ccc91eb8c3c


DoNotUpdateToEdgeWithChromium : 1
PSPath                        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_
                                MACHINE\SOFTWARE\Microsoft\EdgeUpdate
PSParentPath                  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_
                                MACHINE\SOFTWARE\Microsoft
PSChildName                   : EdgeUpdate
PSDrive                       : HKLM
PSProvider                    : Microsoft.PowerShell.Core\Registry



Removing intermediate container 6ccc91eb8c3c
 ---> 7f5d32727b5a
Step 13/16 : RUN Set-Service -Name edgeupdate -Status Stopped -StartupType Disabled # stop edgeupdate service
 ---> Running in 9047b26fdef5
Removing intermediate container 9047b26fdef5
 ---> f0ffbf43fd8d
Step 14/16 : RUN Set-Service -Name edgeupdatem -Status Stopped -StartupType Disabled # stop edgeupdatem service
 ---> Running in b1b351a372ec
Removing intermediate container b1b351a372ec
 ---> 73ccc40479ba
Step 15/16 : RUN Remove-Item -Force -Recurse 'C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\'
 ---> Running in a778cbf23931
Removing intermediate container a778cbf23931
 ---> 8251b1c709f8
Step 16/16 : ENTRYPOINT ["powershell", "-File", "Bootstrap.ps1"]
 ---> Running in dc92a60e1c76
Removing intermediate container dc92a60e1c76
 ---> a1fc750d5546
Successfully built a1fc750d5546
Successfully tagged wingettest:latest
```

All good from me :)

**Review by russellbanks — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Pull request merged**
